import{a as S,S as w,i}from"./assets/vendor-tnUJPedx.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const L="47467192-b15a855f7913b17ade7ea6ded",v="https://pixabay.com/api/",p=async(o,t,s=15)=>{const n={key:L,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:s},{data:e}=await S.get(v,{params:n});return e},m=o=>o.map(({webformatURL:t,largeImageURL:s,tags:n,likes:e,views:r,comments:c,downloads:b})=>`<div class="photo-card">
    <a href="${s}">
    <img src="${t}" alt="${n}" loading="lazy" />
    </a>
    <div class="info">
            <p><b>Likes:</b> ${e}</p>
            <p><b>Views:</b> ${r}</p>
            <p><b>Comments:</b> ${c}</p>
            <p><b>Downloads:</b> ${b}</p>
          </div>
        </div>`).join(""),q=()=>{document.querySelector(".gallery").innerHTML=""},g=o=>{document.querySelector(".gallery").insertAdjacentHTML("beforeend",o)},f=document.querySelector("#search-form"),E=document.querySelector(".gallery"),l=document.querySelector(".loader"),a=document.createElement("button");a.textContent="Load more";a.classList.add("btn");a.style.display="none";document.body.appendChild(a);let h=new w(".gallery a"),u="",d=1,y=0;const P=async o=>{if(o.preventDefault(),u=f.querySelector("input").value.trim(),!u){i.warning({title:"Warning",message:"Please enter a search query!"});return}d=1,q(),l.style.display="block",a.style.display="none";try{const t=await p(u,d);if(y=t.totalHits,l.style.display="none",t.hits.length===0){i.info({title:"Sorry",message:"There are no images matching your search query."});return}i.success({title:"Success",message:`Found ${y} images!`});const s=m(t.hits);g(s),h.refresh(),y>15&&(a.style.display="block")}catch{l.style.display="none",i.error({title:"Error",message:"Something went wrong. Please try again later."})}},$=async()=>{d+=1,l.style.display="block";try{const o=await p(u,d);l.style.display="none";const t=m(o.hits);g(t),h.refresh();const{height:s}=E.firstElementChild.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"}),d*15>=y&&(a.style.display="none",i.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."}))}catch{l.style.display="none",i.error({title:"Error",message:"Something went wrong. Please try again later."})}};f.addEventListener("submit",P);a.addEventListener("click",$);
//# sourceMappingURL=index.js.map
